<?php
// app/design/frontend/default/default/template/recentproducts/recentproducts.phtml
$products = $this­->getRecentProducts();
?>

<div id="product_list">
    <h1>Recent Products</h1>
    <?php if (is_array($products) && count($products)) { ?>
    <?php foreach($products as $product) { ?>
    <div>
        <a href="<?php echo $product['url'] ?>"><?php echo $product['name'] ?></a>
    </div>
    <?php } ?>
    <?php } ?>
</div>
